version: '3'

services:
  evidence-restapi:
    build:   # build using Dockfile in this directory
      context: .
      dockerfile: Dockerfile
    command: sh -c "gunicorn app.main:app 
                      --bind 0.0.0.0:80 
                      --worker-class uvicorn.workers.UvicornH11Worker 
                      --workers ${NUM_WORKERS}
                      --worker-tmp-dir /dev/shm"
    ports:
      - "${API_PORT}:80"
    environment:
      #- EV_PSQL_HOST=localhost
      #- EV_PSQL_PORT=55015
      - EV_PSQL_HOST=172.20.253.5
      - EV_PSQL_PORT=5432
      - EV_PSQL_USERNAME=postgres
      - EV_PSQL_PASSWORD=password1234
    networks:
      evidence-backend-network:
        ipv4_address: 172.20.253.7

networks:
  evidence-backend-network:
    external: true
