version: '3.7'

services:
  evidence-restapi:
    container_name: evidence-restapi
    build:   # build using Dockerfile in this directory
      context: ${RESTAPI_PATH:-.}/
      dockerfile: Dockerfile
    command: sh -c "gunicorn app.main:app 
                      --bind 0.0.0.0:80 
                      --worker-class uvicorn.workers.UvicornH11Worker 
                      --workers ${RESTAPI_NUM_WORKERS:-1}
                      --worker-tmp-dir /dev/shm"
    ports:
      - "${RESTAPI_HOSTPORT}:80"
    environment:
      # Application Database
      # - see database/dbappl.yml
      DBAPPL_HOST: evidence-dbappl_master  # 172.20.253.5
      DBAPPL_PORT: 5432
      DBAPPL_USER: ${DBAPPL_USER:-postgres}
      DBAPPL_PASSWORD: ${DBAPPL_PASSWORD}

      # CORS Exemption Settings
      # - see webapp/webapp.yml
      CORS_WEBAPP_HOSTPORT: ${WEBAPP_HOSTPORT:-8080}
      CORS_WEBAPP_DOMAIN: ${PUBLIC_DOMAIN:-localhost}

      # Authentication Database
      # - see database/dbauth.yml 
      DBAUTH_HOST: evidence-dbauth  # 172.20.253.7
      DBAUTH_PORT: 5432
      DBAUTH_USER: ${DBAUTH_USER:-postgres}
      DBAUTH_PASSWORD: ${DBAUTH_PASSWORD}

      # Access Token Settings
      ACCESS_SECRET_KEY: ${ACCESS_SECRET_KEY}
      ACCESS_TOKEN_EXPIRY: ${ACCESS_TOKEN_EXPIRY:-1440}
      ACCESS_ALGORITHM: ${ACCESS_ALGORITHM:-HS256}

      # Mailer settings for Verification Mails
      SMTP_SERVER: ${SMTP_SERVER:-}  # e.g. "smtp.example.com"
      SMTP_PORT: ${SMTP_PORT:-25}    # 587 (TLS) or 25 (unsecure); 465 (SSL) is not available
      SMTP_TLS: ${SMTP_TLS:-0}       # i.e. "1" or "0"
      SMTP_USER: ${SMTP_USER:-}      # usually just the username, in other cases the full email addr.
      SMTP_PASSWORD: ${SMTP_PASSWORD:-}
      FROM_EMAIL: ${FROM_EMAIL:-}   # e.g. "nobody@example.com"
      VERIFY_PUBLIC_URL: ${VERIFY_PUBLIC_URL:-}   # e.g. "https://mywebapp.com:12345"
      
    networks: [ evidence-network ]  # dynamic IPs!
    # evidence-network:
    #     ipv4_address: 172.20.253.2
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        #window: 300s
